spring.application.name=social-media-backend
server.port=8090
spring.datasource.username= social_3go9_user
spring.datasource.password= 7PgfeARZrPEaqclipnC5OzDrC4ftcjAF
spring.datasource.url= jdbc:postgresql://dpg-d7u9st7lk1mc73efiva0-a.oregon-postgres.render.com/social_3go9?currentSchema=public
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
